version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mongo

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    networks:
      - app-network
    depends_on:
      - fastapi

  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
    volumes:
      - ~/.n8n:/root/.n8n
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
